# name: sample_ci

# on:
#   push:

# jobs:
#     formatter:
#         name: formatter
#         runs-on: ubuntu-latest
#         strategy:
#             matrix:
#                 python-version: [3.9.0]
#         steps:
#           - name: Checkout
#             uses: actions/checkout@v2
#           - name: Set up Python ${{ matrix.python-version }}
#             uses: actions/setup-python@v2
#             with:
#               python-version: ${{ matrix.python-version }}
#           - name: Install Poetry
#             run: |
#               curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
#           - name: Add path for Poetry
#             run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
#           - name: Install Dependencies
#             run: poetry install --no-interaction
#           - name: black
#             run: poetry run black .
#           - name: autoflake
#             run: poetry run autoflake -r .
#           - uses: stefanzweifel/git-auto-commit-action@v3.0.0
#             with:
#               commit_message: Apply Code Formatter Change
#               ref: ${{ github.head_ref }} 

name: Format code # ワークフローの名前を指定

on: # トリガー条件を指定
  pull_request: # プルリクエストに反応
    types: [opened, synchronize] # プルリクエストがオープン、更新された場合にトリガー

jobs: # ジョブの定義を開始
  formatter: # ジョブ名を指定
    name: formatter # ジョブの名前
    runs-on: ubuntu-latest # Ubuntu Linux 上で実行
    strategy: # マトリクス戦略の設定
      matrix:
        python-version: [3.9] # Pythonバージョン3.9を指定
    permissions:
      contents: write # コンテンツに対する書き込み権限を設定
    steps: # ジョブ内のステップの定義を開始
      - name: Checkout Repository # リポジトリのチェックアウト
        uses: actions/checkout@v4 # GitHubリポジトリからコードをチェックアウト
        with:
          ref: ${{ github.head_ref }} # GitHubヘッドリファレンスを指定
      - name: Set up Python ${{ matrix.python-version }} # Python環境のセットアップ
        uses: actions/setup-python@v4 # Python環境のセットアップアクションを使用
        with:
          python-version: ${{ matrix.python-version }} # マトリクスで指定されたPythonバージョンを使用
      - name: Install Dependencies # 依存関係のインストール
        run: |
          python -m pip install --upgrade pip # pipをアップグレード
          pip install autoflake black isort # autoflake、black、isortをインストール
      - name: autoflake # autoflakeを使用してコードを修正
        run: autoflake -r .
      - name: black # blackを使用してコードをフォーマット
        run: black .
      - name: isort # isortを使用してインポートステートメントを整理
        run: isort .
      - name: Auto Commit # 自動コミット
        uses: stefanzweifel/git-auto-commit-action@v5 # 自動コミットアクションを使用
        with:
          commit_message: Apply Code Formatter # コミットメッセージを指定